### ISSUE TITLE
Unable to clone mx-flexray-utils

### ISSUE THREAD

**Issue by jameshilliard** [hostmobility/meta-hostmobility-bsp#4]
The repository [here](https://github.com/hostmobility/meta-hostmobility-bsp/blob/master/recipes-flexray-utils/common/revision.inc) seems to be missing.

**Comment by mattiasbus** [comment]
Hello James,

This is a private repository for our customers who is using our MX-4 hardware. The functionality is optional.  Are you a customer who are using our platforms? You can email support@hostmobility.com.

Best regards,
Mattias

**Comment by jameshilliard** [comment]
> Are you a customer who are using our platforms?

Not yet, I'm looking to see if the MX-4 board's software stack is suitable for a project of mine before purchasing one.
